apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: dev-airecipe

bases:
  - ../../base

namePrefix: ""
nameSuffix: ""

commonLabels:
  environment: dev

patches:
  - target:
      kind: Namespace
    patch: |-
      - op: replace
        path: /metadata/name
        value: dev-airecipe
  - target:
      kind: Ingress
      name: airecipe-ingress
    patch: |-
      - op: replace
        path: /spec/rules/0/host
        value: dev-airecipe.64bit.kr
  - path: hpa-patch.yaml
    target:
      kind: HorizontalPodAutoscaler
      name: airecipe-hpa
