apiVersion: v1
kind: Service
metadata:
  name: airecipe
  namespace: airecipe
  labels:
    app: airecipe
spec:
  type: ClusterIP
  selector:
    app: airecipe
  ports:
  - port: 80
    targetPort: 8000
    protocol: TCP