apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: phoenix-ingress
spec:
  ingressClassName: nginx
  rules:
  - host: phoenix.64bit.kr
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: phoenix
            port:
              number: 6006
