apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

bases:
  - ../../base

resources:
  - ingress.yaml
  - pv-pvc.yaml

images:
  - name: jenkins/jenkins
    newName: jenkins/jenkins
    newTag: lts-jdk17

patchesStrategicMerge:
  - deployment-patch.yaml
